# Generated by Django 5.0.6 on 2024-07-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_jouranlist_alter_article_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jouranlist',
            new_name='Journalist',
        ),
    ]
